// Daily Byte - 27/01/22

/*
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ' '
*/

using System;

namespace Code_Playground
{
    public class Program
    {
        static void Main(string[] args)
        {
            string s = "foobar";
            string t = "barfoot";

            Console.WriteLine(spotTheDifference(s, t));
            Console.ReadLine();
        }

        static char spotTheDifference(string s, string t)
        {
            foreach (char letterT in t)
            {
                if (s.Length == 0)
                {
                    return letterT;
                }

                foreach (char letterS in s)
                {
                    if (letterT == letterS)
                    {
                        //s = s.Replace($"{letterS}", string.Empty);
                        s = s.Remove(s.IndexOf(letterS), 1);
                        break;
                    }
                }
            }
            return ' ';
        }
    }
}